### ISSUE TITLE
Add field for parser

### ISSUE THREAD

**Issue by eumozge** [eumozge/parser-json-python#1]
**Introduction**

A dict of params include a lot of keys and values can be in different params. Will be greate to have a object that can define which type is nesecerry. Also it must validate value and convery to necessery Python type like int, float, list, date, etc.

**TODO**

- [x] Add a class Field
- [x] Add a definition of type
- [x] Add a value validation
- [x] Add a conversion to Python type
- [x] Add the basic Python type like int, float, list and date.
