### ISSUE TITLE
Add FieldBoolean to fields

### ISSUE THREAD

**Issue by alexmitroff** [eumozge/parser-json-python#3]
**Introduction**

We need to be able to parse boolean values.

**TODO**
- [x] Add field
- [x] Add test
- [x] Add FieldBoolean to parser
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Update `setup.py`
